applications:
  prometheus-ceph-exporter:
    charm: cs:prometheus-ceph-exporter
    num_units: 1
relations:
  - [ 'prometheus-ceph-exporter:ceph-exporter', 'prometheus:target' ]
  - [ 'prometheus-ceph-exporter:ceph', '__CEPH_INTERFACE__:client' ]
  - [ telegraf, __CEPH_INTERFACE__ ]
  - [ telegraf, ceph-osd ]
