applications:
  prometheus-ceph-exporter:
    charm: cs:prometheus-ceph-exporter
    num_units: 1
relations:
  - [ 'prometheus-ceph-exporter:ceph-exporter', 'prometheus:target' ]
  - [ 'prometheus-ceph-exporter:ceph', 'ceph-mon:client' ]
  - [ telegraf, ceph-mon ]
  - [ telegraf, ceph-osd ]
