# See https://ubuntu.com/kubernetes/docs/hacluster

applications:
  kubeapi-load-balancer:
    options:
      ha-cluster-vip: __VIP__
  kubeapi-lb-hacluster:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__hacluster
    options:
      cluster_count: __NUM_K8S_LB_UNITS__
relations:
  - [ kubeapi-lb-hacluster, kubeapi-load-balancer ]
