applications:
  flannel:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__flannel
relations:
  - [ 'flannel:cni', 'kubernetes-control-plane:cni' ]
  - [ 'flannel:cni', 'kubernetes-worker:cni' ]
  - [ 'flannel:etcd', 'etcd:db' ]
