applications:
  openstack-integrator:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__openstack-integrator
    constraints: mem=1G
    num_units: 1
relations:
  - [ 'openstack-integrator:clients', 'kubernetes-control-plane:openstack' ]
  - [ 'openstack-integrator:clients', 'kubernetes-worker:openstack' ]
