applications:
  kubeapi-load-balancer:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__kubeapi-load-balancer
    constraints: mem=1G
    expose: true
    num_units: __NUM_K8S_LB_UNITS__
relations:
  - [ 'kubernetes-control-plane:loadbalancer-external', 'kubeapi-load-balancer:lb-consumers' ]
  - [ 'kubernetes-control-plane:loadbalancer-internal', 'kubeapi-load-balancer:lb-consumers' ]
